### PR TITLE
Improves sanitizing sensitive data from Request.__repr__

### PR DESCRIPTION
**Pull request by bjmc**
This is especially important because the entire Request repr() is logged as part of debug logging in various places.

### CODE REVIEW

**Comment by bjmc** [comment]
@thedrow If you have a chance, can you look at this? It's a pretty small change, and it has security implications.

**Comment by rdegges** [comment]
Doh, this broke all my unit tests =D Took a while to figure out what was happening, exactly. But this makes sense. Gonna go rewrite them all =p

**Comment by bjmc** [comment]
@rdegges My apologies! On the plus side, now you're not accidentally logging sensitive information.

**Comment by rdegges** [comment]
Hmm, I think there may potentially? be some issues in the library affected by this. I'm trying to get my tests working again -- here's some output:

```python
self = <tests.mocks.test_api_auth.ApiRequestAuthenticatorTest testMethod=test_basic_api_auth_invalid_credentials>                                                         [341/2458]

    def test_basic_api_auth_invalid_credentials(self):
        app = MagicMock()
        app._client.auth.secret = 'fakeApiKeyProperties.secret'
        app.href = 'HREF'
        api_keys = MagicMock()
        api_keys.get_key = lambda k, s=None: None
        app.api_keys = api_keys
        basic_auth = base64.b64encode('invalid_client_id:invalid_client_secret'.encode('utf-8'))
        uri = 'https://example.com/get'
        http_method = 'GET'
        # body = {}
        body = {'grant_type': 'client_credentials', 'scope': 'test1'}
        headers = {'Authorization': b'Basic ' + basic_auth}
        allowed_scopes = ['test1']

        authenticator = ApiRequestAuthenticator(app)
>       result = authenticator.authenticate(headers=headers, http_method=http_method, uri=uri, body=body, scopes=allowed_scopes)

tests/mocks/test_api_auth.py:126:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
stormpath/api_auth.py:397: in authenticate
    headers, http_method, uri, body, scopes, ttl)
stormpath/api_auth.py:434: in _get_scheme_and_token
    self.app, scopes, http_method, uri, body, headers, ttl)
stormpath/api_auth.py:332: in _get_bearer_token
    uri, http_method, body, headers, {})
../../../../.virtualenvs/stormpath-sdk-python/lib/python2.7/site-packages/oauthlib/oauth2/rfc6749/endpoints/base.py:64: in wrapper
    return f(endpoint, uri, *args, **kwargs)
../../../../.virtualenvs/stormpath-sdk-python/lib/python2.7/site-packages/oauthlib/oauth2/rfc6749/endpoints/token.py:100: in create_token_response
    request, self.default_token_type)
../../../../.virtualenvs/stormpath-sdk-python/lib/python2.7/site-packages/oauthlib/oauth2/rfc6749/grant_types/client_credentials.py:75: in create_token_response
    self.validate_token_request(request)
../../../../.virtualenvs/stormpath-sdk-python/lib/python2.7/site-packages/oauthlib/oauth2/rfc6749/grant_types/client_credentials.py:101: in validate_token_request
    raise errors.InvalidClientError(request=request)
../../../../.virtualenvs/stormpath-sdk-python/lib/python2.7/site-packages/oauthlib/oauth2/rfc6749/errors.py:43: in __init__
    message += ' ' + repr(request)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <[TypeError("expected string or buffer") raised in repr()] SafeRepr object at 0x1039af170>

    def __repr__(self):
        body = self.body
        headers = self.headers.copy()
        if body:
>           body = SANITIZE_PATTERN.sub('\1<SANITIZED>', body)
E           TypeError: expected string or buffer

../../../../.virtualenvs/stormpath-sdk-python/lib/python2.7/site-packages/oauthlib/common.py:419: TypeError
```

It looks like a lot of my issue can be traced back to this: https://github.com/idan/oauthlib/blob/master/oauthlib/oauth2/rfc6749/errors.py#L43

Does that make sense to you at all?

**Comment by bjmc** [comment]
What's a `SafeRepr` ? I don't think that's part of oauthlib. It looks like it's throwing an error where the body is `not None` but also not a string/buffer object that `re.sub()` can operate on. Is there any chance you're replacing the body (or the whole request?) with a Mock object that's behaving oddly?

**Comment by bjmc** [comment]
You've got `body = {'grant_type': 'client_credentials', 'scope': 'test1'}` are you sure that gets properly urlencoded into a string/unicode type?

**Pull request merged**
