### PR TITLE
fix typo in base.py:prepare_authorization_request

### PR DESCRIPTION
**Pull request by lribinik**
fixing self.redirect_uri to self.redirect_url since self.redirect_uri doesn't exist

### CODE REVIEW

**Comment by josephtate** [comment]
Seems like we're missing test coverage for this. Any chance you can add one?

**Comment by lribinik** [comment]
Will work on adding a test.

**Comment by thedrow** [comment]
Already merged with a test in #351. Thanks.

**Comment by lribinik** [comment]
Thanks! (Unfortunately wasn't able to get to it)

**Pull request closed without merging**
