### PR TITLE
#340 - calling getattr on Request should raise an AttributeError if that attribute doesn't exist

### PR DESCRIPTION
**Pull request by kdazzle**
https://github.com/idan/oauthlib/issues/340

Raise an `AttributeError` from `common.Request.__getattr__` so that `getattr` can be used like normal on a request. This commit breaks a lot of existing tests, which I'll fix in another commit.

This might break backwards compatibility if people are relying on `getattr(Request)` automatically returning `None`.

### CODE REVIEW

**Comment by kdazzle** [comment]
Hmm, well a _lot_ of tests fail for a lot of different places around the code. One solution would be to replace all of the assumptions that a request attribute will be either something or `None`, or another would be to provide default values in `Request._params` in the constructor.

**Comment by thedrow** [comment]
I'm really not sure about this one.
Will this change break backwards compatibility?

**Comment by foxx** [comment]
It's certainly the correct way of doing things, and the test appear to pass fine, although there is a chance this might be breaking something which isn't well tested, as well as other people relying on this implementation approach. I'm +1 on this, but will need to be highlighted in the change log.

**Comment by kdazzle** [comment]
Thanks for taking a look at this and for merging it in!
Yeah, as @foxx said, it could break peoples' code if they are relying on that implementation, but I think this change is worth it.

**Pull request merged**
