### PR TITLE
WIP: switch from PyCrypto to cryptography library

### PR DESCRIPTION
**Pull request by singingwolfboy**
PyJWT is now using the [`cryptography`](https://cryptography.io) library internally, and it looks like it's the future of cryptography in Python. (*Way* more understandable!) This is a WIP pull request that starts ripping out PyCrypto and replacing it with `cryptography`. I'm not sure if I'll have time to continue to work on this, so if others want to step up and do the work necessary to finish this pull request, I'd really appreciate it!

### CODE REVIEW

**Comment by tilgovi** [comment]
I think #322 might make this unnecessary.

**Comment by tilgovi** [comment]
Never mind. I see this covers other places where PyCrypto is used.

**Comment by josephtate** [comment]
#322 now replaces PyCrypto completely, so this pull request is obsolete.

**Comment by josephtate** [comment]
@ib-lundgren You can close this as redundant, or @singingwolfboy for that matter.

**Pull request closed without merging**
