### PR TITLE
Improve changelog

### PR DESCRIPTION
**Pull request by svetlyak40wt**
I slightly reformatted changelog and added release dates so it should be more user frendly.
As a bonus, it will be nicely parsed my http://allmychanges.com now.

### CODE REVIEW

**Comment by svetlyak40wt** [comment]
He, watsup? :)

**Comment by svetlyak40wt** [comment]
Well, nobody cares!

**Comment by pypingou** [comment]
Looking at https://github.com/idan/oauthlib/graphs/contributors the activity is clearly up and down, so just wait there is no hurry and there was no new release so..

**Comment by ib-lundgren** [comment]
@svetlyak40wt sorry for merging this so late :( Contributions like this are awesome but I've not been able to find any time whatsoever for oauthlib for absolute ages now. Sorry about this!

**Comment by svetlyak40wt** [comment]
Thank you, @ib-lundgren . Better later than never :)

**Pull request merged**
